(function() {var implementors = {};
implementors["logins"] = [{"text":"impl IntoFfi for PasswordInfo <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;PasswordInfo: Message,&nbsp;</span>","synthetic":false,"types":[]},{"text":"impl IntoFfi for PasswordInfos <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;PasswordInfos: Message,&nbsp;</span>","synthetic":false,"types":[]}];
implementors["places"] = [{"text":"impl IntoFfi for SearchResultList <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;SearchResultList: Message,&nbsp;</span>","synthetic":false,"types":[]},{"text":"impl IntoFfi for TopFrecentSiteInfos <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;TopFrecentSiteInfos: Message,&nbsp;</span>","synthetic":false,"types":[]},{"text":"impl IntoFfi for HistoryVisitInfos <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;HistoryVisitInfos: Message,&nbsp;</span>","synthetic":false,"types":[]},{"text":"impl IntoFfi for HistoryVisitInfosWithBound <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;HistoryVisitInfosWithBound: Message,&nbsp;</span>","synthetic":false,"types":[]},{"text":"impl IntoFfi for BookmarkNode <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;BookmarkNode: Message,&nbsp;</span>","synthetic":false,"types":[]},{"text":"impl IntoFfi for BookmarkNodeList <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;BookmarkNodeList: Message,&nbsp;</span>","synthetic":false,"types":[]},{"text":"impl IntoFfi for HistoryMetadata <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;HistoryMetadata: Message,&nbsp;</span>","synthetic":false,"types":[]},{"text":"impl IntoFfi for HistoryMetadataList <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;HistoryMetadataList: Message,&nbsp;</span>","synthetic":false,"types":[]},{"text":"impl IntoFfi for PublicNode <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;BookmarkNode: From&lt;PublicNode&gt; + IntoFfi,&nbsp;</span>","synthetic":false,"types":[]}];
implementors["push"] = [{"text":"impl IntoFfi for DispatchInfo <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;DispatchInfo: Message,&nbsp;</span>","synthetic":false,"types":[]},{"text":"impl IntoFfi for KeyInfo <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;KeyInfo: Message,&nbsp;</span>","synthetic":false,"types":[]},{"text":"impl IntoFfi for SubscriptionInfo <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;SubscriptionInfo: Message,&nbsp;</span>","synthetic":false,"types":[]},{"text":"impl IntoFfi for SubscriptionResponse <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;SubscriptionResponse: Message,&nbsp;</span>","synthetic":false,"types":[]},{"text":"impl IntoFfi for PushSubscriptionChanged <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;PushSubscriptionChanged: Message,&nbsp;</span>","synthetic":false,"types":[]},{"text":"impl IntoFfi for PushSubscriptionsChanged <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;PushSubscriptionsChanged: Message,&nbsp;</span>","synthetic":false,"types":[]}];
implementors["rc_log_ffi"] = [{"text":"impl IntoFfi for LogAdapterState <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;LogAdapterState: Send,&nbsp;</span>","synthetic":false,"types":[]}];
implementors["sql_support"] = [{"text":"impl IntoFfi for SqlInterruptHandle <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;SqlInterruptHandle: Send,&nbsp;</span>","synthetic":false,"types":[]}];
implementors["sync15_traits"] = [{"text":"impl IntoFfi for SyncTelemetryPing <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;SyncTelemetryPing: Serialize,&nbsp;</span>","synthetic":false,"types":[]}];
implementors["sync_manager"] = [{"text":"impl IntoFfi for SyncResult <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;SyncResult: Message,&nbsp;</span>","synthetic":false,"types":[]},{"text":"impl IntoFfi for SyncParams <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;SyncParams: Message,&nbsp;</span>","synthetic":false,"types":[]}];
implementors["tabs"] = [{"text":"impl IntoFfi for ClientsTabs <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;ClientsTabs: Message,&nbsp;</span>","synthetic":false,"types":[]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()